name = "venture-rp-api"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "venture-rp"
database_id = "7a77dcba-9d99-46cc-bcdb-cd56aca5aac9"

[vars]
DISCORD_CLIENT_ID = "1539798080470257755"
DISCORD_GUILD_ID = "934623765344714804"
OWNER_USER_IDS = "329302709956116483,581215588706287619"
SITE_URL = "https://scapecodes.github.io/VentureRP/"
SITE_ORIGIN = "https://scapecodes.github.io"
FIVEM_STATUS_URL = "http://209.222.101.135:30099/dynamic.json"
FIVEM_JOIN_URL = "fivem://connect/209.222.101.135:30099"
